name: Pipeline Test

on:
    push:
        branches:
        - main
        paths:
        - data/**
        - project/**

jobs:
    test-pipeline:
        runs-on: ubuntu-latest
        steps:
        - name: Check out code
          uses: actions/checkout@v3

        - name: Set up Python 3.11
          uses: actions/setup-python@v4
          with:
            python-version: 3.11

        - name: Pipeline Test
          run: | 
            chmod +x ./project/tests.sh
            ./project/tests.sh
